### ISSUE TITLE
SVG Logo 

### ISSUE THREAD

**Issue by versable** [oxidecomputer/design.oxide.computer#19]
Hey Jessie!

Do you guys have a SVG logo of Oxide Computer on hand? If not, would you like one? It would be super useful for animating it, or collapsing the light/dark logo into one file and triggering the color change via CSS.

Thanks,

Mike

**Comment by jessfraz** [comment]
Oh we do not have one, but I do have the AI files and an EPS, GitHub will not let me upload either tho...

**Comment by jessfraz** [comment]
I will push to the repo under static :)

**Comment by jessfraz** [comment]
They are here, hopefully that helps! https://github.com/oxidecomputer/design.oxide.computer/tree/master/static/files

**Comment by versable** [comment]
Thanks!

Looks like @fivenp already took care of the conversion with the PR #18 (I tried it with Inkscape and the ai file, was really easy)
